server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

  
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets (added mp3, mp4)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|txt|mp3|mp4)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
}
